// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDii6Y7E5vkrF4lwRnfHpupeRGSt6yMAzc',
    appId: '1:1015107089929:web:ddeb3e02c96d8375012ad8',
    messagingSenderId: '1015107089929',
    projectId: 'healthmate-d1f3c',
    authDomain: 'healthmate-d1f3c.firebaseapp.com',
    databaseURL: 'https://healthmate-d1f3c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthmate-d1f3c.appspot.com',
    measurementId: 'G-EZ253PTTYE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8FTiXCtR0m2V_Hvxdot9RCiEiSy57RGA',
    appId: '1:1015107089929:ios:9e9c94f8811e1f0a012ad8',
    messagingSenderId: '1015107089929',
    projectId: 'healthmate-d1f3c',
    databaseURL: 'https://healthmate-d1f3c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthmate-d1f3c.appspot.com',
    iosBundleId: 'com.example.heathmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDii6Y7E5vkrF4lwRnfHpupeRGSt6yMAzc',
    appId: '1:1015107089929:web:193ad5ac2c451967012ad8',
    messagingSenderId: '1015107089929',
    projectId: 'healthmate-d1f3c',
    authDomain: 'healthmate-d1f3c.firebaseapp.com',
    databaseURL: 'https://healthmate-d1f3c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthmate-d1f3c.appspot.com',
    measurementId: 'G-N4XJFDSFB8',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8FTiXCtR0m2V_Hvxdot9RCiEiSy57RGA',
    appId: '1:1015107089929:ios:9e9c94f8811e1f0a012ad8',
    messagingSenderId: '1015107089929',
    projectId: 'healthmate-d1f3c',
    databaseURL: 'https://healthmate-d1f3c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthmate-d1f3c.appspot.com',
    iosBundleId: 'com.example.heathmate',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIOvC-_OYx-L7Q49J9qKfox0aadNjXA2k',
    appId: '1:1015107089929:android:590dc23d48053c8d012ad8',
    messagingSenderId: '1015107089929',
    projectId: 'healthmate-d1f3c',
    databaseURL: 'https://healthmate-d1f3c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthmate-d1f3c.appspot.com',
  );

}